import json
import re

with open('examplesToTranslate.json', 'r', encoding='utf-8') as f:
    examples = json.load(f)

translations = [
    "Cu?c h?p du?c lên l?ch vào th? Hai.",
    "Vui lòng n?p tru?c h?n chót.",
    "Cô ?y dã n?p báo cáo hàng tháng.",
    "B?n làm vi?c ? phòng ban nào?",
    "T?t c? nhân viên ph?i tham gia bu?i dào t?o.",
    "Ngu?i qu?n lý dã phê duy?t ngân sách.",
    "Hãy liên h? v?i ngu?i giám sát c?a b?n d? du?c phê duy?t.",
    "Các d?ng nghi?p c?a tôi r?t h? tr?.",
    "Tr? s? chính n?m ? New York.",
    "Chúng tôi có các chi nhánh ? 10 thành ph?.",
    "Ðon hàng c?a b?n dã du?c xác nh?n.",
    "Cô ?y dã mua 3 s?n ph?m tr?c tuy?n.",
    "Gi? l?i biên lai c?a b?n d? d?i tr?.",
    "Hóa don dã du?c g?i qua email.",
    "Thành viên nh?n du?c gi?m giá 10%.",
    "Yêu c?u hoàn ti?n trong vòng 30 ngày.",
    "Ð?i hàng du?c phép trong vòng 14 ngày.",
    "Giao hàng mi?n phí cho các don hàng trên .",
    "Lô hàng dã d?n sáng nay.",
    "M?t hàng này dã h?t hàng.",
    "Chuy?n bay kh?i hành lúc 7 gi? sáng.",
    "Ki?m tra gi? kh?i hành t?i C?ng B3.",
    "Th?i gian d?n d? ki?n là 3 gi? chi?u.",
    "Quá trình lên máy bay b?t d?u tru?c 30 phút.",
    "Tôi mu?n d?t ch? tru?c.",
    "Ch? ? dã du?c bao g?m trong gói.",
    "L?ch trình chuy?n di dã du?c xác nh?n.",
    "Không có phí hành lý ph? thu.",
    "Khai báo hàng hóa t?i h?i quan.",
    "Yêu c?u có h? chi?u h?p l?.",
    "Ngân sách hàng nam dã du?c phê duy?t.",
    "Theo dõi t?t c? các chi phí kinh doanh m?t cách c?n th?n.",
    "Doanh thu tang tru?ng 15% trong nam ngoái.",
    "Công ty dã t?o ra l?i nhu?n dáng k?.",
    "Công ty dã báo cáo m?t kho?n l? ròng.",
    "Ð?u tu dài h?n mang l?i l?i nhu?n t?t hon.",
    "Ðang ký kho?n vay kinh doanh tr?c tuy?n.",
    "Lãi su?t là 5% m?i nam.",
    "N?p h? so khai thu? c?a b?n tru?c ngày 15 tháng 4.",
    "Ki?m tra s? du tài kho?n c?a b?n tr?c tuy?n.",
    "Tôi có m?t cu?c h?n v?i nha si lúc 2 gi? chi?u.",
    "Phòng khám m? c?a t? th? Hai d?n th? B?y.",
    "Du?c si dã kê don thu?c cho tôi.",
    "Ðau d?u là m?t tri?u ch?ng ph? bi?n c?a b?nh cúm.",
    "Bác si dã d? xu?t m?t phuong pháp di?u tr? m?i.",
    "Bác si dang khám b?nh cho b?nh nhân.",
    "B?o hi?m c?a b?n có chi tr? cho ca ph?u thu?t này không?",
    "Bác si s? ki?m tra b?n ngay bây gi?.",
    "Anh ?y m?t m?t tu?n d? ph?c h?i sau con c?m l?nh.",
    "U?ng thu?c này sau b?a an.",
    "Vui lòng thông báo cho chúng tôi v? b?t k? thay d?i nào.",
    "Cu?c h?p dã du?c hoãn l?i d?n th? Nam.",
    "S? ki?n dã b? h?y do th?i ti?t x?u.",
    "Tuân th? chính sách c?a công ty m?i lúc.",
    "Th? t?c dã du?c c?p nh?t.",
    "Chúng tôi dang tuy?n d?ng cho 5 v? trí.",
    "N?p don ?ng tuy?n c?a b?n tru?c th? Sáu.",
    "G?i so y?u lý l?ch c?a b?n cho phòng nhân s?.",
    "Cu?c ph?ng v?n di?n ra vào th? Tu.",
    "Chúng tôi dã thuê 10 nhân viên m?i.",
    "Chúng tôi có m?t v? trí dang m? cho ch?c v? này.",
    "Có m?t v? trí tr?ng trong phòng k? toán.",
    "Yêu c?u trình d? chuyên môn cao.",
    "Ðua ra m?c luong c?nh tranh.",
    "Các quy?n l?i bao g?m b?o hi?m y t?.",
    "Áp d?ng th?i gian th? vi?c 3 tháng.",
    "Cô ?y s? ngh? huu vào cu?i nam nay.",
    "Vui lòng cung c?p hai ngu?i gi?i thi?u.",
    "Quá trình gi?i thi?u nhân viên m?i b?t d?u vào ngày d?u tiên c?a b?n.",
    "Chúng tôi dã thuê m?t không gian van phòng nh?.",
    "H?p d?ng thuê h?t h?n vào tháng t?i.",
    "B?t d?ng s?n này n?m ? trung tâm thành ph?.",
    "Ch? nhà dã d?ng ý s?a mái nhà.",
    "Ngu?i thuê nhà ph?i tr? ti?n thuê vào ngày d?u tiên.",
    "Chúng tôi dang tìm ki?m m?t d?a di?m thu?n ti?n.",
    "H? dã c?i t?o nhà b?p vào nam ngoái.",
    "Anh ?y dã cho thuê l?i phòng c?a mình trong su?t mùa hè.",
    "Chúng tôi dã tr? m?t kho?n ti?n d?t c?c b?ng m?t tháng ti?n thuê.",
    "Ki?m tra ngôi nhà tru?c khi mua.",
    "Nu?c và di?n là các ti?n ích.",
    "Can h? du?c trang b? d?y d? n?i th?t.",
    "Ð?u b?p dã chu?n b? m?t món an d?c bi?t.",
    "Tôi có th? xem th?c don du?c không?",
    "Bia và nu?c có ga là các d? u?ng ph? bi?n.",
    "Chúng tôi dã d?t ch? cho b?n ngu?i.",
    "Th?c an r?t ngon nhung ph?c v? l?i ch?m.",
    "Hãy d? l?i ti?n boa cho ngu?i ph?c v?.",
    "Tr?n t?t c? các nguyên li?u vào m?t cái bát.",
    "Chi?c bánh sô cô la này r?t ngon.",
    "Cô ?y di?u hành m?t d?ch v? cung c?p d? an u?ng.",
    "Hãy d?c các dánh giá nhà hàng tru?c khi di.",
    "Chúng tôi dã g?i món khai v? tru?c.",
    "Cá là món an chính yêu thích c?a tôi.",
    "Làm theo công th?c d? n?u món này."
]

with open('J:/Leaning English Website/client/angel-english/src/data/toeic30DaysData.js', 'r', encoding='utf-8') as f:
    lines = f.readlines()

for i, ex in enumerate(examples):
    idx = ex['index']
    vietnamese = translations[i]
    lines[idx] = re.sub(r'(example:\s*"[^"]+")', r'\1, exampleVi: "' + vietnamese + '"', lines[idx])

with open('J:/Leaning English Website/client/angel-english/src/data/toeic30DaysData.js', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Injected successfully!")
