const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');
require('dotenv').config();

// Dictionary of manual POS mappings for specific words that might be tricky
const posMap = {
    // Verbs
    "decide": "Động từ (v)",
    "focus": "Động từ (v)",
    "accept": "Động từ (v)",
    "support": "Động từ (v)",
    "negotiate": "Động từ (v)",
    "obligate": "Động từ (v)",
    "convince": "Động từ (v)",
    "compromise": "Động từ (v)",
    "prepare": "Động từ (v)",
    "advertise": "Động từ (v)",
    "attract": "Động từ (v)",
    "compare": "Động từ (v)",
    "accommodate": "Động từ (v)",
    "announce": "Động từ (v)",
    "gather": "Động từ (v)",
    "address": "Động từ (v)",
    "evaluate": "Động từ (v)",
    "hold": "Động từ (v)",
    "determine": "Động từ (v)",
    "establish": "Động từ (v)",
    "designate": "Động từ (v)",
    "believe": "Động từ (v)",
    "develop": "Động từ (v)",
    "contribute": "Động từ (v)",
    "promote": "Động từ (v)",
    "risk": "Động từ (v)",
    "change": "Động từ (v)",
    "complain": "Động từ (v)",
    "return": "Động từ (v)",
    "replace": "Động từ (v)",
    "refund": "Động từ (v)",
    "invest": "Động từ (v)",
    "solve": "Động từ (v)",
    "order": "Động từ (v)",
    "guarantee": "Động từ (v)",
    "access": "Động từ (v)",
    "facilitate": "Động từ (v)",
    "install": "Động từ (v)",
    "hesitate": "Động từ (v)",
    "contact": "Động từ (v)",
    "expand": "Động từ (v)",
    "recruit": "Động từ (v)",
    "submit": "Động từ (v)",
    "hire": "Động từ (v)",
    "choose": "Động từ (v)",
    "compensate": "Động từ (v)",
    "relocate": "Động từ (v)",
    "sign": "Động từ (v)",
    "assign": "Động từ (v)",
    "demonstrate": "Động từ (v)",
    "fire": "Động từ (v)",
    "fulfill": "Động từ (v)",
    "consult": "Động từ (v)",
    "check": "Động từ (v)",
    "remind": "Động từ (v)",
    "provide": "Động từ (v)",
    "verify": "Động từ (v)",
    "charge": "Động từ (v)",
    "estimate": "Động từ (v)",
    "receive": "Động từ (v)",
    "activate": "Động từ (v)",
    "forecast": "Động từ (v)",
    "subscribe": "Động từ (v)",
    "publish": "Động từ (v)",
    "celebrate": "Động từ (v)",
    "expire": "Động từ (v)",
    "renew": "Động từ (v)",
    "discontinue": "Động từ (v)",
    "donate": "Động từ (v)",
    "renovate": "Động từ (v)",
    "interrupt": "Động từ (v)",
    "reschedule": "Động từ (v)",
    "reimburse": "Động từ (v)",
    "encourage": "Động từ (v)",
    "expect": "Động từ (v)",
    "implement": "Động từ (v)",
    "seek": "Động từ (v)",
    "instruct": "Động từ (v)",
    "organize": "Động từ (v)",
    "allow": "Động từ (v)",
    "commit": "Động từ (v)",
    "reflect": "Động từ (v)",
    "postpone": "Động từ (v)",
    "obtain": "Động từ (v)",
    "maintain": "Động từ (v)",
    "recognize": "Động từ (v)",
    "disclose": "Động từ (v)",
    "reveal": "Động từ (v)",
    "assess": "Động từ (v)",
    "assemble": "Động từ (v)",
    "avoid": "Động từ (v)",
    "participate in": "Động từ (v)",
    "make efforts": "Động từ (v)",
    "carry out": "Động từ (v)",
    "undergo": "Động từ (v)",
    "innovate": "Động từ (v)",
    "retire": "Động từ (v)",
    "consider": "Động từ (v)",
    "compose": "Động từ (v)",
    "launch": "Động từ (v)",

    // Nouns
    "party": "Danh từ (n)",
    "deposit": "Danh từ (n)",
    "strategy": "Danh từ (n)",
    "product": "Danh từ (n)",
    "customer": "Danh từ (n)",
    "quality": "Danh từ (n)",
    "brochure": "Danh từ (n)",
    "discount": "Danh từ (n)",
    "purchase": "Danh từ (n)",
    "demonstration": "Danh từ (n)",
    "benefit": "Danh từ (n)",
    "speech": "Danh từ (n)",
    "membership": "Danh từ (n)",
    "meeting": "Danh từ (n)",
    "headquarters": "Danh từ (n)",
    "accountant": "Danh từ (n)",
    "technician": "Danh từ (n)",
    "plan": "Danh từ (n)",
    "goal": "Danh từ (n)",
    "revenue": "Danh từ (n)",
    "branch": "Danh từ (n)",
    "experience": "Danh từ (n)",
    "interview": "Danh từ (n)",
    "supplier": "Danh từ (n)",
    "budget": "Danh từ (n)",
    "salary": "Danh từ (n)",
    "opportunity": "Danh từ (n)",
    "initiative": "Danh từ (n)",
    "colleague": "Danh từ (n)",
    "opinion": "Danh từ (n)",
    "manufacturer": "Danh từ (n)",
    "price": "Danh từ (n)",
    "company": "Danh từ (n)",
    "computer": "Danh từ (n)",
    "productivity": "Danh từ (n)",
    "printer": "Danh từ (n)",
    "network": "Danh từ (n)",
    "software": "Danh từ (n)",
    "document": "Danh từ (n)",
    "copy": "Danh từ (n)",
    "data": "Danh từ (n)",
    "disk": "Danh từ (n)",
    "process": "Danh từ (n)",
    "detail": "Danh từ (n)",
    "announcement": "Danh từ (n)",
    "supervisor": "Danh từ (n)",
    "position": "Danh từ (n)",
    "candidate": "Danh từ (n)",
    "applicant": "Danh từ (n)",
    "requirement": "Danh từ (n)",
    "qualification": "Danh từ (n)",
    "permanent contract": "Danh từ (n)",
    "contribution": "Danh từ (n)",
    "award": "Danh từ (n)",
    "campaign": "Danh từ (n)",
    "reputation": "Danh từ (n)",
    "item": "Danh từ (n)",
    "merchandise": "Danh từ (n)",
    "catalog": "Danh từ (n)",
    "warehouse": "Danh từ (n)",
    "mistake": "Danh từ (n)",
    "policy": "Danh từ (n)",
    "warranty": "Danh từ (n)",
    "delivery": "Danh từ (n)",
    "charge": "Danh từ (n)",
    "estimate": "Danh từ (n)",
    "bank": "Danh từ (n)",
    "account": "Danh từ (n)",
    "transaction": "Danh từ (n)",
    "cashier": "Danh từ (n)",
    "identification": "Danh từ (n)",
    "signature": "Danh từ (n)",
    "forecast": "Danh từ (n)",
    "accounting": "Danh từ (n)",
    "investor": "Danh từ (n)",
    "real estate": "Danh từ (n)",
    "apartment": "Danh từ (n)",
    "competitor": "Danh từ (n)",
    "magazine": "Danh từ (n)",
    "issue": "Danh từ (n)",
    "voucher": "Danh từ (n)",
    "author": "Danh từ (n)",
    "athlete": "Danh từ (n)",
    "career": "Danh từ (n)",
    "achievement": "Danh từ (n)",
    "audience": "Danh từ (n)",
    "charity fund": "Danh từ (n)",
    "admission": "Danh từ (n)",
    "capacity": "Danh từ (n)",
    "ticket": "Danh từ (n)",
    "proposal": "Danh từ (n)",
    "approval": "Danh từ (n)",
    "office": "Danh từ (n)",
    "parking lot": "Danh từ (n)",
    "survey": "Danh từ (n)",
    "questionnaire": "Danh từ (n)",
    "feedback": "Danh từ (n)",
    "facility": "Danh từ (n)",
    "office supplies": "Danh từ (n)",
    "expense": "Danh từ (n)",
    "project": "Danh từ (n)",
    "résumé": "Danh từ (n)",
    "partner": "Danh từ (n)",
    "seminar/workshop": "Danh từ (n)",
    "event": "Danh từ (n)",
    "secretary": "Danh từ (n)",
    "receptionist": "Danh từ (n)",
    "assistant": "Danh từ (n)",
    "executive": "Danh từ (n)",
    "invitation": "Danh từ (n)",
    "president": "Danh từ (n)",
    "feature": "Danh từ (n)",
    "representative": "Danh từ (n)",
    "version": "Danh từ (n)",
    "payment": "Danh từ (n)",
    "destination": "Danh từ (n)",
    "flight": "Danh từ (n)",
    "demand": "Danh từ (n)",
    "plane": "Danh từ (n)",
    "accomplishment": "Danh từ (n)",
    "leading firm": "Danh từ (n)",
    "advantage": "Danh từ (n)",
    "market share": "Danh từ (n)",
    "operation": "Danh từ (n)",
    "service": "Danh từ (n)",
    "priority": "Danh từ (n)",
    "chef": "Danh từ (n)",
    "recipe": "Danh từ (n)",
    "variety": "Danh từ (n)",
    "dish": "Danh từ (n)",
    "local community": "Danh từ (n)",
    "bakery": "Danh từ (n)",
    "popularity": "Danh từ (n)",
    "profit": "Danh từ (n)",
    "recipient": "Danh từ (n)",
    "damage": "Danh từ (n)",
    "staff": "Danh từ (n)",
    "driver's license": "Danh từ (n)",
    "concert": "Danh từ (n)",
    "dedication": "Danh từ (n)",
    "employee": "Danh từ (n)",
    "reminder": "Danh từ (n)",
    "anniversary": "Danh từ (n)",
    "ceremony": "Danh từ (n)",
    "renovation": "Danh từ (n)",
    "spacious interior": "Danh từ (n)",
    "design": "Danh từ (n)",
    "number": "Danh từ (n)",
    "attendee": "Danh từ (n)",
    "advance ticket": "Danh từ (n)",
    "museum": "Danh từ (n)",
    "entertainment": "Danh từ (n)",
    "elevator": "Danh từ (n)",
    "expert": "Danh từ (n)",
    "vacation": "Danh từ (n)",
    "conference center": "Danh từ (n)",
    "reservation": "Danh từ (n)",
    "procedure": "Danh từ (n)",
    "choice": "Danh từ (n)",
    "result": "Danh từ (n)",
    "trouble": "Danh từ (n)",
    "company": "Danh từ (n)",
    "division": "Danh từ (n)",
    "presence": "Danh từ (n)",
    "gift": "Danh từ (n)",
    "market": "Danh từ (n)",

    // Adjectives
    "surprised": "Tính từ (adj)",
    "affordable": "Tính từ (adj)",
    "well-attended": "Tính từ (adj)",
    "various": "Tính từ (adj)",
    "impressed": "Tính từ (adj)",
    "defective": "Tính từ (adj)",
    "outdated": "Tính từ (adj)",
    "reasonable": "Tính từ (adj)",
    "urgent": "Tính từ (adj)",
    "considerably": "Trạng từ (adv)",
    "compatible": "Tính từ (adj)",
    "confidential": "Tính từ (adj)",
    "negotiable": "Tính từ (adj)",
    "consistently": "Trạng từ (adv)",
    "eligible": "Tính từ (adj)",
    "available": "Tính từ (adj)",
    "crucial": "Tính từ (adj)",
    "long-term": "Tính từ (adj)",
    "famous": "Tính từ (adj)",
    "consecutive": "Tính từ (adj)",
    "reliable/dependable": "Tính từ (adj)",
    "strictly confidential": "Trạng từ (adv)",
    "comprehensive knowledge of": "Tính từ (adj)",
    "potential": "Tính từ (adj)",
    "international": "Tính từ (adj)",
    "positive": "Tính từ (adj)",
    "extremely": "Trạng từ (adv)",
    "approximately": "Trạng từ (adv)",
    "recently": "Trạng từ (adv)",
    "capable of": "Tính từ (adj)",
    "especially": "Trạng từ (adv)",
    "competitive": "Tính từ (adj)",
    "restricted": "Tính từ (adj)",
    "exclusive": "Tính từ (adj)",
    "unique": "Tính từ (adj)",
    "officially": "Trạng từ (adv)",
    "obviously": "Trạng từ (adv)",
    "specific": "Tính từ (adj)",
    "delicious": "Tính từ (adj)",
    "significant": "Tính từ (adj)",
    "valid": "Tính từ (adj)",
    "complimentary": "Tính từ (adj)",
    "temporary": "Tính từ (adj)",
    "durable": "Tính từ (adj)",
    "brief": "Tính từ (adj)",
    "productive": "Tính từ (adj)",
    "expected": "Tính từ (adj)",
    "sufficient": "Tính từ (adj)",
    "essential": "Tính từ (adj)",
    "currently": "Trạng từ (adv)",

    // Adverbs & Others
    "therefore": "Trạng từ (adv)",
    "however": "Trạng từ (adv)",
    "relatively": "Trạng từ (adv)",
    "carefully": "Trạng từ (adv)",
    "promptly": "Trạng từ (adv)",
    "accurately": "Trạng từ (adv)",
    "unfortunately": "Trạng từ (adv)",

    // Phrases
    "breach (the contract)": "Cụm động từ (v)",
    "sign the contract": "Cụm động từ (v)",
    "customer satisfaction": "Cụm danh từ (n)",
    "lower price": "Cụm danh từ (n)",
    "grand opening": "Cụm danh từ (n)",
    "convenient location": "Cụm danh từ (n)",
    "special offer": "Cụm danh từ (n)",
    "free shipping": "Cụm danh từ (n)",
    "apply for": "Cụm động từ (v)",
    "head of sales department": "Cụm danh từ (n)",
    "increase sales": "Cụm động từ (v)",
    "responsible for": "Cụm tính từ (adj)",
    "human resources department": "Cụm danh từ (n)",
    "stay competitive": "Cụm động từ (v)",
    "make sure": "Cụm động từ (v)",
    "training session": "Cụm danh từ (n)",
    "technical support": "Cụm danh từ (n)",
    "reply to": "Cụm động từ (v)",
    "lack of": "Cụm danh từ (n)",
    "application form": "Cụm danh từ (n)",
    "enclose/attach": "Động từ (v)",
    "at least": "Cụm trạng từ (adv)",
    "work overtime": "Cụm động từ (v)",
    "go on business": "Cụm động từ (v)",
    "shortly thereafter": "Cụm trạng từ (adv)",
    "take part in": "Cụm động từ (v)",
    "permanent contract": "Cụm danh từ (n)",
    "medical coverage": "Cụm danh từ (n)",
    "performance review": "Cụm danh từ (n)",
    "buy in bulk": "Cụm động từ (v)",
    "no extra cost": "Cụm danh từ (n)",
    "outstanding bill": "Cụm danh từ (n)",
    "intend to": "Cụm động từ (v)",
    "public transportation": "Cụm danh từ (n)",
    "excellent service": "Cụm danh từ (n)",
    "reasonable price": "Cụm danh từ (n)",
    "best seller": "Cụm danh từ (n)",
    "take place": "Cụm động từ (v)",
    "charity fund": "Cụm danh từ (n)",
    "in advance": "Cụm trạng từ (adv)",
    "as planned": "Cụm trạng từ (adv)",
    "specialize in": "Cụm động từ (v)",
    "outdoor activities": "Cụm danh từ (n)",
    "guided tour": "Cụm danh từ (n)",
    "make a reservation": "Cụm động từ (v)",
    "tight budget": "Cụm danh từ (n)",
    "under construction": "Cụm tính từ (adj)",
    "on schedule": "Cụm trạng từ (adv)",
    "ahead of schedule": "Cụm trạng từ (adv)",
    "behind schedule": "Cụm trạng từ (adv)",
    "fill the vacant position": "Cụm động từ (v)",
    "familiarity with": "Cụm danh từ (n)",
    "figure out": "Cụm động từ (v)",
    "handle problem": "Cụm động từ (v)",
    "in a timely manner": "Cụm trạng từ (adv)",
    "in charge of": "Cụm tính từ (adj)",
    "comply with/abide by/adhere to": "Cụm động từ (v)",
    "look for": "Cụm động từ (v)",
    "fill out a form": "Cụm động từ (v)",
    "hand in": "Cụm động từ (v)",
    "terms and conditions": "Cụm danh từ (n)",
    "have a tendency to": "Cụm động từ (v)",
    "come up with": "Cụm động từ (v)",
    "reasonable price/rate": "Cụm danh từ (n)",
    "outstanding accomplishment": "Cụm danh từ (n)",
    "cut cost": "Cụm động từ (v)",
    "disclose/reveal": "Động từ (v)",
    "assess/evaluate": "Động từ (v)",
    "to be eager to": "Cụm tính từ (adj)",
    "instead of": "Cụm giới từ (prep)",
    "express delivery": "Cụm danh từ (n)",
    "to be exempt from": "Cụm tính từ (adj)",
    "as long as": "Cụm liên từ (conj)",
    "accompanied by": "Cụm động từ (v)",
    "prior to": "Cụm giới từ (prep)",
    "extend our sincere thanks": "Cụm động từ (v)",
    "keep an appointment": "Cụm động từ (v)",
    "under any circumstances": "Cụm trạng từ (adv)",
    "as part of": "Cụm giới từ (prep)",
    "as anticipated": "Cụm trạng từ (adv)"
};

(async () => {
    try {
        console.log('Finding and fixing ALL remaining uncategorized "Từ vựng" entries...');

        const jsonPath = path.join(__dirname, '..', '..', 'client', 'angel-english', 'src', 'data', 'data.json');
        let dataWords = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

        let fixedCount = 0;
        const stillUncategorized = [];

        dataWords = dataWords.map(w => {
            if (!w.category || w.category === 'Từ vựng' || w.category.trim() === '') {
                const enLower = (w.en || '').toLowerCase().trim();
                let mapped = posMap[enLower] || posMap[w.en];

                if (!mapped) {
                    // Smart fallback inference
                    const viLower = (w.vi || '').toLowerCase().trim();
                    if (enLower.endsWith('ly')) mapped = 'Trạng từ (adv)';
                    else if (enLower.endsWith('tion') || enLower.endsWith('ment') || enLower.endsWith('ity') || enLower.endsWith('ness') || enLower.endsWith('er') || enLower.endsWith('or') || enLower.endsWith('ship')) mapped = 'Danh từ (n)';
                    else if (enLower.endsWith('able') || enLower.endsWith('ible') || enLower.endsWith('ive') || enLower.endsWith('ic') || enLower.endsWith('al') || enLower.endsWith('ous') || enLower.endsWith('ful')) mapped = 'Tính từ (adj)';
                    else if (viLower.startsWith('sự ') || viLower.startsWith('người ') || viLower.startsWith('cuộc ') || viLower.startsWith('cái ') || viLower.startsWith('nhà ') || viLower.startsWith('tờ ') || viLower.startsWith('bản ') || viLower.startsWith('buổi ')) mapped = 'Danh từ (n)';
                    else if (viLower.startsWith('làm ') || viLower.startsWith('gửi ') || viLower.startsWith('tăng ') || viLower.startsWith('giảm ') || viLower.startsWith('tổ chức ') || viLower.startsWith('xác định ') || viLower.startsWith('đánh giá ') || viLower.startsWith('phát biểu ') || viLower.startsWith('đăng ký ')) mapped = 'Động từ (v)';
                    else if (viLower.startsWith('rất ') || viLower.startsWith('tương đối ') || viLower.startsWith('liên tục ') || viLower.startsWith('ngay ') || viLower.startsWith('gần đây ')) mapped = 'Trạng từ (adv)';
                    else if (enLower.includes(' ')) mapped = 'Cụm từ (phrase)';
                    else mapped = 'Danh từ (n)'; // Default standard fallback for nouns
                }

                w.category = mapped;
                fixedCount++;
            }
            return w;
        });

        // Write back to data.json
        fs.writeFileSync(jsonPath, JSON.stringify(dataWords, null, 2), 'utf8');
        console.log(`Successfully fixed ${fixedCount} words in data.json! Zero "Từ vựng" remaining.`);

        // Also update Database
        const connection = await mysql.createConnection({
            host: process.env.DB_HOST || 'localhost',
            user: process.env.DB_USER || 'root',
            password: process.env.DB_PASSWORD || '123456',
            database: process.env.DB_NAME || 'server_learning_english'
        });

        for (const w of dataWords) {
            await connection.query(
                'UPDATE words SET category = ? WHERE id = ?',
                [w.category, w.id]
            );
        }

        console.log('Successfully updated MySQL database records!');
        await connection.end();
    } catch (err) {
        console.error('Error finding and fixing uncategorized words:', err);
    }
})();
